### ISSUE TITLE
Changing the look

### ISSUE THREAD

**Issue by simplekjl** [CodelightStudios/Android-Smart-Login#10]
Hello, I know that this is a module but I don't know if you have a feature that allows  you to change sizes of the buttons ( FB and G+) or change the colors of the Ui or the background?, also to translate the strings to other languages.

Best Regards

**Comment by kalyandechiraju** [comment]
Hi @simplekjl  those options would be nice additions. The current plan was to give the user an option to show a custom layout as the login page. Again as you said giving full control over the existing page would also be very nice to have.

**Comment by kalyandechiraju** [comment]
Merging with issue #5
