### ISSUE TITLE
Ability to hide or display Toolbar

### ISSUE THREAD

**Issue by simplekjl** [CodelightStudios/Android-Smart-Login#11]
In your example images you show a login without toolbar, how que can I hide the toolbar?

**Comment by kalyandechiraju** [comment]
The Toolbar in the new login page is hidden by default (this new page will be available in the next release). Currently, there is no option to hide or display toolbar for the existing page. Anyhow planning to have the option to add a custom layout as the login page.

**Comment by kalyandechiraju** [comment]
@simplekjl The new version 1.x is now completely independent of login layout. Check out README for more details. Project Wiki will be ready soon.
