### ISSUE TITLE
When's the next release?

### ISSUE THREAD

**Issue by techscientist** [CodelightStudios/Android-Smart-Login#15]
Hi, I would like to know when the next release is scheduled?

Also, what still needs to be done? I might be able to help with what needs to be done (currently busy with school work, though).

**Comment by kalyandechiraju** [comment]
Hi @techscientist thinking of releasing the next version with custom layout support and adding the library as Gradle dependency. Once they are added, will release with other bug fixes as well (the current open issues).

I would really love your support. Please take up any open issue and send a pull request. (Do let all of us know the issues that are being fixed.)
