### ISSUE TITLE
Facebook email is not returned in the json response (email permission is added)

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [CodelightStudios/Android-Smart-Login#16]

**Comment by kalyandechiraju** [comment]
Hi @AlaeddineOuerteni I will look into the issue. Meanwhile, can you confirm that the user (who is logging in) accepted the email read permission when granting permissions for your app while logging in?

**Comment by AlaeddineOuerteni** [comment]
Hi @kalyandechiraju, thank you for your answer. Yes, the permission is accepted and I tested with many users and many Facebook apps, it's always the same issue.

**Comment by AlaeddineOuerteni** [comment]
Related to a change in the Graph API v2.4 which makes it necessary that you specify every field you want to have returned from the Graph API.

final Bundle bundle = new Bundle();
bundle.putString("fields", "id,name,email");
request.setParameters(bundle);
request.executeAsync();

**Comment by kalyandechiraju** [comment]
Hi @AlaeddineOuerteni with these permissions passed into the library, the facebook login returned the email of the logged in user without any code change.

```java
ArrayList<String> permissions = new ArrayList<>();
                    permissions.add("public_profile");
                    permissions.add("email");
                    permissions.add("user_birthday");
                    permissions.add("user_friends");
```

Please check once and confirm.

**Comment by kalyandechiraju** [comment]
Tested again, working fine if proper permissions are passed.
