### ISSUE TITLE
Please enter a valid email

### ISSUE THREAD

**Issue by AliAmjad** [CodelightStudios/Android-Smart-Login#18]
On Custom Signup even after providing a valid email address the app is still throwing this error, is it a bug?

**Comment by kalyandechiraju** [comment]
Thanks for pointing it out. It is because of the missing NOT operator before the email pattern matcher.

```java
        else if(!Patterns.EMAIL_ADDRESS.matcher(email).matches()){
            //DialogUtil.getErrorDialog(R.string.invalid_email_error, this).show();
            emailSignup.setError(getResources().getText(R.string.invalid_email_error));
            emailSignup.requestFocus();
        } 
```

**Comment by agenco12** [comment]
I tried to register, but still in the email error, how do I fix?

**Comment by kalyandechiraju** [comment]
@agenco12 I suspect you are using 0.5 version which is given as the link in the readme. Can you clone this library and try by adding the project as a module to your existing library?

**Comment by agenco12** [comment]
could you tell me how to import the library as a module in Android Studio and delete the files .aar?
