### ISSUE TITLE
Facebook error

### ISSUE THREAD

**Issue by rohansood42** [CodelightStudios/Android-Smart-Login#19]
Only gets profile name and nothing else.

**Comment by kalyandechiraju** [comment]
Hi @rohansood42 Can I know What permissions have you sent into the login config? These are the permissions am using and I was getting the info properly.

```java
ArrayList<String> permissions = new ArrayList<>();
                    permissions.add("public_profile");
                    permissions.add("email");
                    permissions.add("user_birthday");
                    permissions.add("user_friends");
```

**Comment by rohansood42** [comment]
I am also sending this not getting the information.

**Comment by rohansood42** [comment]
User birthday is no longer allowed by Facebook without submission.

**Comment by kalyandechiraju** [comment]
Facebook has now limited user information to the public profile. Check out the new version 1.x and let me know if the issue persists. Check out README for more details. Project Wiki will be ready soon.
