### ISSUE TITLE
I want to hide logins except Google-login

### ISSUE THREAD

**Issue by Rainer-Lang** [CodelightStudios/Android-Smart-Login#2]
For now  I use my own login activity. Google-login should be used so I hided the other possibilities to login. The user has to click on an arrow and then facebook, digits and own login (username/password) is shown.
Would be nice if this lib could do this job.

**Comment by kalyandechiraju** [comment]
Are you saying this?
When you set like this, you will be shown only Google login.(you can explicitly set other options to false or you can set just what you need)
```java
Intent intent = loginBuilder.with(context)
                        .isGoogleLoginEnabled(true)
                        .build();
    startActivityForResult(intent, SmartLoginConfig.LOGIN_REQUEST);
```

If that is what you are looking for, then please take a look at [Sample app](https://github.com/CodelightStudios/Android-Smart-Login/blob/master/app/src/main/java/studios/codelight/smartlogin/MainActivity.java)

**Comment by Rainer-Lang** [comment]
I want that the user could login via Google, Facebook, Digits and custom. But first the user should only see Google-login. Is this possible?

**Comment by Rainer-Lang** [comment]
Should say this in other way: User could toggle show "google-login" or show "all login options" - in the login activity.

**Comment by kalyandechiraju** [comment]
Yeah yeah I got it :+1:

**Comment by Rainer-Lang** [comment]
That's because Google-login is preferred on Android (of course) ;-)

**Comment by kalyandechiraju** [comment]
Exactly. I dont think that is implemented in this version, will add it soon :+1:

**Comment by Rainer-Lang** [comment]
I looked at really many login-libs - and yours looks really best - but I need digits and "toggle show".

**Comment by kalyandechiraju** [comment]
Thank you so much. :+1:  I will definitely add those features soon.

**Comment by Rainer-Lang** [comment]
I have to thank YOU! :-)

**Comment by kalyandechiraju** [comment]
@Rainer-Lang Check out the new version 1.x which is now completely independent of the login layout. Check out README for more details. Project Wiki will be ready soon.
