### ISSUE TITLE
Facebook/Google picture url

### ISSUE THREAD

**Issue by komlan55** [CodelightStudios/Android-Smart-Login#20]
It would be great if we could get the profile picture url

**Comment by kalyandechiraju** [comment]
@komlan55 I would definitely add that property for FacebookUser. Currently GoogleUser Profile picture url is available. 

`googleUser.getPhotoUrl()`

**Comment by kalyandechiraju** [comment]
The SmartGoogleUser has the photoUrl as string property in the new version 1.x. Check out README for more details. Project Wiki will be ready soon.
