### ISSUE TITLE
using custom view for sign up

### ISSUE THREAD

**Issue by walaagomaa18** [CodelightStudios/Android-Smart-Login#24]
hi,

how can i create my own view for sign up, and does not use the library view??

is it avilable?

**Comment by kalyandechiraju** [comment]
Hi @walaagomaa18 Currently its unavailable. But you can tweak the page as you like by adding the complete project as a module instead of adding aar file. 

Hope that helps! I have plans to improve with custom layout options.

**Comment by kalyandechiraju** [comment]
@walaagomaa18 The library is updated to version 1.x and can now you can have your own custom UI for login page. Check out README for more details. Project Wiki will be ready soon.
