### ISSUE TITLE
Login screen layout

### ISSUE THREAD

**Issue by agenco12** [CodelightStudios/Android-Smart-Login#28]
1) Is it possible to change texts? Because I want translate texts in my language. How?
2) Is it possible to change background? How?

**Comment by kalyandechiraju** [comment]
@agenco12 Currently this is not possible using the aar dependency. However, if you take the source code and add the library as a module, you can edit the layout file as you like without changing the IDs of the views.

Currently, I am working to provide an option to use any custom layout with the library. Will update the library and wiki along with that release.

**Comment by agenco12** [comment]
you tell me how to import the library as a module? I have imported the .aar file, how should I proceed?

**Comment by kalyandechiraju** [comment]
select new > import Android module option > select the smart login library folder from the repo. this should work.

**Comment by agenco12** [comment]
@kalyandechiraju Before adding the module should I remove the dependencies of Gradle and .aar module? After I download the repo, import the module and select the folder androidsmartlibrary?

**Comment by kalyandechiraju** [comment]
yes remove the existing aar file and import new module

**Comment by kalyandechiraju** [comment]
Gradle dependency of compile project is needed

**Comment by kalyandechiraju** [comment]
@agenco12 Now the UI logic is removed from the framework. With version 1.x you can have your own login layout and call the framework API's. Check out README for more details. Project Wiki will be ready soon.
