### ISSUE TITLE
Please add login with Twitter

### ISSUE THREAD

**Issue by techscientist** [CodelightStudios/Android-Smart-Login#3]
Hi,

Nice library, guys! This is excellent. Can you guys please add login with Twitter and phone number via Twitter fabric and digits, or something like that? Login with twitter would be very needed for a login.

Also, I think I can rework the login page.

**Comment by kalyandechiraju** [comment]
Yes @techscientist 
1. Twitter and Fabric additions are in the queue.
2. Wanted to redesign the login page with material design and also the option to add custom layouts.

**Comment by kalyandechiraju** [comment]
Merging this issue with Issue https://github.com/CodelightStudios/Android-Smart-Login/issues/1
