### ISSUE TITLE
Figured out the previous one, new issue. When I click on the back button built within the app it takes me to the screenshot below.

### ISSUE THREAD

**Issue by khuranadhruv18** [CodelightStudios/Android-Smart-Login#33]
![image](https://cloud.githubusercontent.com/assets/25913367/23200555/ccdcaeb0-f889-11e6-97d3-d94c06616ee2.png)

I would either like to remove that title at the top (where it shows "log in" and the <- button), or be able to redirect the user to this page:
![image](https://cloud.githubusercontent.com/assets/25913367/23200607/0b6b5ca8-f88a-11e6-876a-56baed21a3bb.png)

Thanks!

**Comment by kalyandechiraju** [comment]
@khuranadhruv18 Check out the new version (1.x) with improved framework logic and decoupled UI with the framework. Now you can have your own UI and call the SmartLogin API's.
