### ISSUE TITLE
I want to add source code as project instead of .aar file

### ISSUE THREAD

**Issue by WalaaMaq** [CodelightStudios/Android-Smart-Login#34]
I want to add source code as project instead of .aar file , how to do this and which folder to add as library ... and i wonder if .aar file has the same version as source code ?? .. thanks in advance

**Comment by kalyandechiraju** [comment]
@WalaaMaq You can now add the project via gradle dependency which will be updated with stable releases. If you want to add it as a module with source code, download the git repo and copy the smartloginlibrary folder as a module to your existing project.
