### ISSUE TITLE
Problems with doFacebookLogin in old version!

### ISSUE THREAD

**Issue by khuranadhruv18** [CodelightStudios/Android-Smart-Login#37]
LoginManager.getInstance().logInWithReadPermissions(SmartLoginActivity.this, permissions);
            LoginManager.getInstance().registerCallback(callbackManager, new FacebookCallback<LoginResult>() {
                @Override
                public void onSuccess(LoginResult loginResult) {
                    progress.setMessage(getString(R.string.getting_data));
                    GraphRequest request = GraphRequest.newMeRequest(loginResult.getAccessToken(), new GraphRequest.GraphJSONObjectCallback() {
                        @Override
                        public void onCompleted(JSONObject object, GraphResponse response) {
                            progress.dismiss();
                            UserUtil util = new UserUtil();
                            SmartFacebookUser facebookUser = util.populateFacebookUser(object);
                            if (facebookUser != null) {
                                finishLogin(facebookUser);
                            } else {
                                finish();
                            }
                        }
                    });
                    request.executeAsync();
                }

This is your old code. It's not populating the util correctly and it's not allowing me to use the users data

**Comment by omgninja** [comment]
I think the newer version (from gradle) have the same issue as well

**Comment by khuranadhruv18** [comment]
I have figured out the problem: you need to create a bundle with permissions before you do the request.executeAsync();
