### ISSUE TITLE
The output of the UI is different what is in the screenshot

### ISSUE THREAD

**Issue by whaleswallace** [CodelightStudios/Android-Smart-Login#38]
The UI Layout is different from what is in the screenshots. For instance I couldn't recreate this particular view below as it is in the screenshots:
<img width="306" alt="screen shot 2017-07-08 at 12 55 49 pm" src="https://user-images.githubusercontent.com/5219986/27985121-f1a10d0e-63dc-11e7-9f93-98a4d6f2a029.png">

**Comment by kalyandechiraju** [comment]
The newer version of the library has no layout associated with it. Instead, you can build your own customisable UI for your login page. The image in readme file is just a sample login page.
