### ISSUE TITLE
Support for custom sign in/signout/signup with remote server

### ISSUE THREAD

**Issue by techscientist** [CodelightStudios/Android-Smart-Login#4]
I have a remote backend django app that has all rest endpoints for user management. The authentication type is via a token (Token authentication, not JWT).

How would I integrate this with custom signup/sign in/signout?

**Comment by kalyandechiraju** [comment]
Doesn't this work for you?
Implement **SmartCustomLoginListener** in your Activity which has *customSignin*, *customSignup* and *customUserSignout* methods where you can implement your logic.
