### ISSUE TITLE
node Backend lib suggestion to use with Android-Smart-Login

### ISSUE THREAD

**Issue by davida5** [CodelightStudios/Android-Smart-Login#40]
Hi Guys, This is not a problem with the lib, but I couldn't find any other way to reach out.

I am wondering if you have any suggestions for using a lib for the backend handling of all three login strategies?
Or is the only option to write it from scratch?
Thank you so much

**Comment by kalyandechiraju** [comment]
@davida5 Hi David, Can you be more descriptive on your requirements for "backend handling"?

**Comment by davida5** [comment]
I am looking for a starting library with a RESTful API to handle the calls and authorization (standard calls for endpoints http://mydomain/login , http://mydomain/logout ), also for FB login there could be other calls that are available from FB API.  I'm looking for node.js lib
