### ISSUE TITLE
Add support for user-definable login layout

### ISSUE THREAD

**Issue by techscientist** [CodelightStudios/Android-Smart-Login#5]
I think we can make this library more modular by allowing the user to specify a login layout/fragment. He/she would also have to include the facebook/google login button ids via an attribute.

What do you guys think?

**Comment by kalyandechiraju** [comment]
Hi @techscientist I do have the similar idea. It would be a great addition.

**Comment by kalyandechiraju** [comment]
@techscientist New version 1.x is now completely independent of login UI. Check out README for more details. Project Wiki will be ready soon.
