### ISSUE TITLE
Add support for email instead of username

### ISSUE THREAD

**Issue by techscientist** [CodelightStudios/Android-Smart-Login#9]
Instead of strictly requiring the username field as a username, allow the developer to configure whether an email will be used instead of a username.

What do you think?

**Comment by kalyandechiraju** [comment]
That will be a good option!!

**Comment by kalyandechiraju** [comment]
Implement like this:

```java
Intent intent = loginBuilder.with(getApplicationContext())
                            .setAppLogo(getlogo())
                            .isFacebookLoginEnabled(facebookLogin.isChecked())
                            .withFacebookAppId(getString(R.string.facebook_app_id)).withFacebookPermissions(permissions)
                            .isGoogleLoginEnabled(googleLogin.isChecked())
                            .isCustomLoginEnabled(customLogin.isChecked(), SmartLoginConfig.LoginType.withEmail)
                            .setSmartCustomLoginHelper(MainActivity.this)
                            .build();
```

You can pass one of the `LoginType` to the `isCustomLoginEnabled` method.

```java
public enum LoginType {
    withEmail,
    withUsername
}
```

If `LoginType.withEmail` is selected, the returned `SmartUser` will have the email property set along with the password. Else if `LoginType.withUsername` is selected, then the returned `SmartUser` will have the username property set along with the password.

**Comment by kalyandechiraju** [comment]
This feature will be available in the next release.
